#ifndef _STALE_H
#define _STALE_H

#define EKRAN_WYSOKOSC 600
#define EKRAN_SZEROKOSC 800

#define KLATKI_NA_SEKUNDE 150

#define BOHATER_SZEROKOSC 35
#define BOHATER_WYSOKOSC 35

#define POZIOM_WYSOKOSC 600
#define POZIOM_SZEROKOSC 1600

#define KAFEL_WYSOKOSC 40
#define KAFEL_SZEROKOSC 40

#endif // _STALE_H
